# Generated by Django 2.2 on 2019-05-20 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanlybanhang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hanghoa',
            name='khuyenmai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quanlybanhang.KhuyenMai'),
        ),
    ]
